/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;



/**
 *
 * @author maria
 */
public class GestionUniversidad extends javax.swing.JFrame {

    
    //ESTEBAN
    /**
     * Creates new form GestionUniversidad
     */
    public GestionUniversidad() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Escritorio = new javax.swing.JDesktopPane();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        gestionAlumnos = new javax.swing.JMenu();
        itemAlumnos = new javax.swing.JMenuItem();
        itemMateria = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemInscripcione = new javax.swing.JMenuItem();
        itemNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemAlumnosMaterias = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Universidad La Punta");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        Escritorio.setLayer(escritorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        gestionAlumnos.setText("Gestionar Alumnos");

        itemAlumnos.setText("Alumnos");
        itemAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlumnosActionPerformed(evt);
            }
        });
        gestionAlumnos.add(itemAlumnos);

        jMenuBar1.add(gestionAlumnos);

        itemMateria.setText("Gestionar Materias");

        jMenuItem2.setText("Materias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        itemMateria.add(jMenuItem2);

        jMenuBar1.add(itemMateria);

        jMenu1.setText("Administración");

        itemInscripcione.setText("Manejo de Inscripciones");
        itemInscripcione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInscripcioneActionPerformed(evt);
            }
        });
        jMenu1.add(itemInscripcione);

        itemNotas.setText("Manejo de Notas");
        itemNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNotasActionPerformed(evt);
            }
        });
        jMenu1.add(itemNotas);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Consultas");

        itemAlumnosMaterias.setText("Alumnos por materia");
        itemAlumnosMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlumnosMateriasActionPerformed(evt);
            }
        });
        jMenu4.add(itemAlumnosMaterias);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaAlumno va = new VistaAlumno();
        va.setLocation(
                (Escritorio.getWidth() - va.getWidth()) / 2,
                (Escritorio.getHeight() - va.getHeight()) / 2
        );
        va.setVisible(true);
        escritorio.add(va);
        escritorio.moveToFront(va);
        
    }//GEN-LAST:event_itemAlumnosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaMateria materiaFrame = new VistaMateria();
        materiaFrame.setLocation(
                (Escritorio.getWidth() - materiaFrame.getWidth()) / 2,
                (Escritorio.getHeight() - materiaFrame.getHeight()) / 2
        );
        Escritorio.add(materiaFrame);
        materiaFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void itemAlumnosMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlumnosMateriasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaListarInscripciones vi = new VistaListarInscripciones();
        vi.setLocation(
                (Escritorio.getWidth() - vi.getWidth()) / 2,
                (Escritorio.getHeight() - vi.getHeight()) / 2
        );
        vi.setVisible(true);
        escritorio.add(vi);
        escritorio.moveToFront(vi);
    }//GEN-LAST:event_itemAlumnosMateriasActionPerformed

    private void itemInscripcioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInscripcioneActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaInscripcion vi = new VistaInscripcion();
        vi.setLocation(
                (Escritorio.getWidth() - vi.getWidth()) / 2,
                (Escritorio.getHeight() - vi.getHeight()) / 2
        );
        vi.setVisible(true);
        escritorio.add(vi);
        escritorio.moveToFront(vi);
    }//GEN-LAST:event_itemInscripcioneActionPerformed

    private void itemNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNotasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaCargaNotas vi = new VistaCargaNotas();
        vi.setLocation(
                (Escritorio.getWidth() - vi.getWidth()) / 2,
                (Escritorio.getHeight() - vi.getHeight()) / 2
        );
        vi.setVisible(true);
        escritorio.add(vi);
        escritorio.moveToFront(vi);
    }//GEN-LAST:event_itemNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUniversidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu gestionAlumnos;
    private javax.swing.JMenuItem itemAlumnos;
    private javax.swing.JMenuItem itemAlumnosMaterias;
    private javax.swing.JMenuItem itemInscripcione;
    private javax.swing.JMenu itemMateria;
    private javax.swing.JMenuItem itemNotas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
