/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Alumno;
import Modelo.Inscripcion;
import Modelo.Materia;
import Persistencia.AlumnoData;
import Persistencia.InscripcionData;
import Persistencia.MateriaData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class VistaInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaInscripcion
     */
    
    private InscripcionData inscData = new InscripcionData();
    private MateriaData mData  = new MateriaData();
    private AlumnoData aData = new AlumnoData();
    private List<Materia> listaM = mData.listarMaterias();
    private List<Alumno> listaA = aData.listarAlumnos();

    private DefaultTableModel modelo = new DefaultTableModel();

    public VistaInscripcion() {
        initComponents();
        cargaAlumnos();
        armarCabeceraTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbSeleccionarAlumno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jrbInscriptos = new javax.swing.JRadioButton();
        jrbNoInscriptos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMuestraInscriptos = new javax.swing.JTable();
        btnInscribir = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbAnularInscribir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Formulario Inscripcion");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Formulario Inscripcion");

        jLabel2.setText("Seleccione un alumno:");

        jcbSeleccionarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSeleccionarAlumnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Listado de Materias");

        jrbInscriptos.setText("Materias Inscriptas");
        jrbInscriptos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbInscriptosMouseClicked(evt);
            }
        });
        jrbInscriptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInscriptosActionPerformed(evt);
            }
        });

        jrbNoInscriptos.setText("Materias no Inscriptas");
        jrbNoInscriptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNoInscriptosActionPerformed(evt);
            }
        });

        jtMuestraInscriptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtMuestraInscriptos);

        btnInscribir.setBackground(new java.awt.Color(204, 204, 204));
        btnInscribir.setText("Inscribir");
        btnInscribir.setEnabled(false);
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(204, 204, 204));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbAnularInscribir.setBackground(new java.awt.Color(204, 204, 204));
        jbAnularInscribir.setText("Anular Inscripcion");
        jbAnularInscribir.setEnabled(false);
        jbAnularInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbInscriptos)
                                .addGap(56, 56, 56)
                                .addComponent(jrbNoInscriptos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(jcbSeleccionarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnInscribir)
                .addGap(39, 39, 39)
                .addComponent(jbAnularInscribir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbSeleccionarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbNoInscriptos)
                    .addComponent(jrbInscriptos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAnularInscribir)
                    .addComponent(jbSalir)
                    .addComponent(btnInscribir))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbInscriptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInscriptosActionPerformed
        borrarFilaTabla();
        jrbNoInscriptos.setSelected(false);
        cargaDatosInscriptas();
        jbAnularInscribir.setEnabled(true);
        btnInscribir.setEnabled(false);
    }//GEN-LAST:event_jrbInscriptosActionPerformed

    private void jcbSeleccionarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSeleccionarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSeleccionarAlumnoActionPerformed

    private void jrbInscriptosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbInscriptosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbInscriptosMouseClicked

    private void jrbNoInscriptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNoInscriptosActionPerformed
        borrarFilaTabla();
        //jrbInscriptos.setEnabled(false);
        jrbInscriptos.setSelected(false);
        cargaDatosNoInscriptas();
        jbAnularInscribir.setEnabled(false);
        btnInscribir.setEnabled(true);
    }//GEN-LAST:event_jrbNoInscriptosActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        int filaSeleccionada = jtMuestraInscriptos.getSelectedRow();
        if (filaSeleccionada != -1) {
            Alumno a = (Alumno) jcbSeleccionarAlumno.getSelectedItem();

            // verifica que el alumno este activo
            if (a != null && !a.isEstado()) {
                JOptionPane.showMessageDialog(this, "No se puede inscribir a un alumno inactivo.");
                return;
            }

            String nombreMateria = (String) modelo.getValueAt(filaSeleccionada, 1);
            Materia m = mData.buscarMateria(nombreMateria);

            // verifica que la materia este activa
            if (m != null && !m.isEstado()) {
                JOptionPane.showMessageDialog(this, "No se puede inscribir a una materia inactiva.");
                return;
            }

            Inscripcion i = new Inscripcion(a, m, 0);
            inscData.guardarInscripcion(i);
            borrarFilaTabla();

            // recargar las materias no inscriptas
            cargaDatosNoInscriptas();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una materia para inscribir.");
        }

    }//GEN-LAST:event_btnInscribirActionPerformed

    private void jbAnularInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscribirActionPerformed
         int filaSeleccionada = jtMuestraInscriptos.getSelectedRow();
    if (filaSeleccionada != -1) {
        Alumno a = (Alumno) jcbSeleccionarAlumno.getSelectedItem();
        
        // verifica que el alumno este activa
        if (a != null && !a.isEstado()) {
            JOptionPane.showMessageDialog(this, "El alumno seleccionado está inactivo.");
            return;
        }
        
        int idMateria = (Integer) modelo.getValueAt(filaSeleccionada, 0);
        
        // verifica que la materia este activa
        Materia m = mData.buscarMateriaPorId(idMateria);
        if (m != null && !m.isEstado()) {
            JOptionPane.showMessageDialog(this, "La materia seleccionada está inactiva.");
            return;
        }
        
        inscData.borrarInscripcion(a.getIdAlumno(), idMateria);
        
        // recargar las materias inscriptas
        cargaDatosInscriptas();
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una materia para anular la inscripción.");
    }
    }//GEN-LAST:event_jbAnularInscribirActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed
    private void cargaAlumnos() {
        for (Alumno item : listaA) {
            if (item.isEstado()) {
                jcbSeleccionarAlumno.addItem(item);
            }
        }
    }

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Año");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        jtMuestraInscriptos.setModel(modelo);
    }

    private void borrarFilaTabla() {
        modelo.setRowCount(0);
    }

    private void cargaDatosNoInscriptas() {
        //borrarFilasTabla();
        Alumno selec = (Alumno) jcbSeleccionarAlumno.getSelectedItem();
        
        listaM = inscData.obtenerMateriasNoCursadas(selec.getIdAlumno());
        
        for (Materia m : listaM) {
            modelo.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAnio()});
        }

        
    }

    private void cargaDatosInscriptas() {
        //borrarFilasTabla();
        Alumno selec = (Alumno) jcbSeleccionarAlumno.getSelectedItem();
        if (selec != null && !selec.isEstado()) {
            JOptionPane.showMessageDialog(this, "El alumno seleccionado está inactivo.");
            jbAnularInscribir.setEnabled(false);
            return;
        }
        List<Materia> lista = inscData.obtenerMateriasCursadas(selec.getIdAlumno());
       
        for (Materia m : lista) {
            modelo.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAnio()});
        }

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnularInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Alumno> jcbSeleccionarAlumno;
    private javax.swing.JRadioButton jrbInscriptos;
    private javax.swing.JRadioButton jrbNoInscriptos;
    private javax.swing.JTable jtMuestraInscriptos;
    // End of variables declaration//GEN-END:variables
}
